version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=Asia/Shanghai
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - "/usr/local/work/docker/project/zmr/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes --requirepass zgh564739784
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: oegrt
      MONGO_INITDB_ROOT_PASSWORD: qweqwecz123dsfs12shawe
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: oegrt
     # MONGO_INITDB_ROOT_PASSWORD: qweqwecz123dsfs12shawe
    volumes:
      - "/usr/local/work/docker/project/zmr/mongodb:/data/db"
    deploy: 
      restart_policy:
        condition: on-failure
      replicas: 1
    command: [--auth]
  mongo-express:
    image: mongo-express
    ports:
      - "8081:80"
    environment:
      TZ: Asia/Shanghai
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: oegrt
      ME_CONFIG_MONGODB_ADMINPASSWORD: qweqwecz123dsfs12shawe
    volumes:
      - "/etc/localtime:/etc/localtime"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
  zoo1:
    image: zookeeper:3.4
    volumes:
      - "/etc/localtime:/etc/localtime"
    #restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      #SET_CONTAINER_TIMEZONE: true
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9093:9092"
    environment:
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.3.207:9092
      TZ: Asia/Shanghai
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      #KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      #- SET_CONTAINER_TIMEZONE=true
      #- CONTAINER_TIMEZONE=Asia/Shanghai
    depends_on:
      - zoo1
